urls.py
from django.conf.urls.defaults import *
import settings
from django.contrib.auth.views import login, logout_then_login, logout
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from master import page as mpage

urlpatterns = patterns('',
    # Example:
    # (r'^reco/', include('reco.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^util/', include('utils.urls')),
    
    url(r'^logout$', logout, {'next_page': '/'}),
    url(r'^$', mpage.CreateQuotePage(), name='master_landing_page'),
    url(r'^cq$', mpage.CreateQuotePage(), name = 'master_cq_page'),
    url(r'^quote/(?P<quote>\w+)$', mpage.QuotePage(), name='master_quote_page'),
    url(r'^project/(?P<code>.+)$', mpage.LandingPage(), name='master_project_page'),
    url(r'^search$', mpage.SearchPage(), name='master_search_page')

)
urlpatterns += patterns("django.views",
        url(r"^%s(?P<path>.*)/$" % settings.MEDIA_URL[1:], "static.serve", {
            "document_root": settings.MEDIA_ROOT,
        })
    )

utils/urls.py
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
# To change this template, choose Tools | Templates
# and open the template in the editor.

__author__="naved"
__date__ ="$22 Jun, 2010 1:42:04 PM$"

urlpatterns = patterns('', url(r'^callback', 'utils.ajax.get_callback', name='ajax_url'), )
 

master/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
import hashlib
def hash(id):
    h = hashlib.new('ripemd160')
    h.update(str(id))
    return h.hexdigest()
# Create your models here.
DOC_CHOICES = (
		('NT', 'Note'),
                ('CO', 'Court Opinion'),
                ('ST', 'Statute'),
                ('RL', 'Regulation'),
                ('MM', 'Memo'),
                ('BR', 'Brief'),
                ('JO', 'Journal'),
                ('AR', 'Article'),
                ('WS', 'Website'),
                ('OT', 'Other'),
)

class Quote(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    link = models.CharField(max_length=255, blank = True, null=True)
    text = models.TextField()
    group = models.ForeignKey('EmailCode', blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    doc_type = models.CharField(max_length=2, choices=DOC_CHOICES)
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now = True)
    references = models.ManyToManyField("Reference")
    is_public = models.BooleanField()

    def save(self, force_insert=False, force_update=False):
        super(Quote, self).save(force_update=force_update, force_insert=force_insert)
        self.link = hash(self.id)
        super(Quote, self).save(force_update=True, force_insert=False)
        
class Reference(models.Model):
    url = models.URLField(blank=True, null=True)
    text = models.CharField(max_length=255,blank=True, null=True)

class EmailCode(models.Model):
    email = models.EmailField(unique=True)
    code = models.CharField(max_length=100, unique = True)
    
class Tag(models.Model):
    text = models.CharField(max_length=100)
    quote = models.ForeignKey('Quote')

class QuoteBin(models.Model):
    user = models.ForeignKey(User)
    name = models.TextField()
    quote = models.ManyToManyField('Quote')

master/forms.py
#!/usr/bin/env python
#
#       forms.py
#       
#       Copyright 2009 Yousuf Fauzan <yousuffauzan@gmail.com>
#       
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(_("Please enter a correct username and password. Note that both fields are case-sensitive."))
            elif not self.user_cache.is_active:
                raise forms.ValidationError(_("This account is inactive."))


class SignupForm(forms.Form):
    username = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    
    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(_("A user with that username already exists."))

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(_("The two password fields didn't match."))
        return password2

templates/base.html
{% spaceless %}
<!DOCTYPE html>
<html>
<script> document.domain = document.domain; </script>
<head>
  <title>{% block title %} Quote by Tabulaw {% endblock %}</title>
  <meta name="description" content="Collect, store and organize your quotes."/>
  <meta name="keywords" content="law, legal, lawyer, attorney, law school, briefs, court"/>
  <meta http-equiv="Content-Type" content="text/html;charset=utf8" />
  <link rel="icon" href="/static/images/favicon.ico" type="image/x-icon"> 
  <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon"> 
  <link rel="stylesheet" type="text/css" href="/static/css/common/reset.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/base.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/master/footer.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/browser_specific/ie_specific.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/browser_specific/opera_specific.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/jqtransform.css" />
  
{% for c in css %}
  <link rel="stylesheet" type="text/css" href="{{c}}" />
{% endfor %}
  <script type="text/javascript" src="/static/js/jquery.js"></script>
  <script type="text/javascript" src="/static/js/base.js"></script>
  <script  type="text/javascript" src="/static/js/css_browser_selector.js"></script>
  <script  type="text/javascript" src="/static/js/jquery.jqtransform.js"></script>
  {% if USER %}
  <script type="text/javascript" src="/static/js/Orbited.js"></script>
  <script type="text/javascript" src="/static/js/lzOrbited.js">  </script>
  {% endif %}

{% for j in js %}
  <script type="text/javascript" src="{{j}}"></script>
{% endfor %}
  {% block extra_head %}
  {% endblock %}
<script type="text/javascript">
	AJAX_URL = "{% url ajax_url %}";
	{% if USER %}
	USER = true;
	{% else %}
	USER = false;
	{% endif %}
	
	$(function() {
	  //find all forms with class jqtransform and apply the plugin
	  $("form.transform select").parent('.rowElem').jqTransform();
	});
</script>
<script type="text/javascript">



</script>

</head>

<body>
  {% block js_templates %} {% endblock %}
  <div id="wrapper">        
        {% block header %} {% endblock %}
        {% block main_body %} {% endblock %}
		 <div class="push"></div>
  </div>
  {% include "master/footer.html" %}
  <div class="clear"></div>
</body>

</html>
{% endspaceless %}

templates/common/BoxBlank.html
{% for t in tabs %}
{{ t.html }}
{% endfor %}

templates/common/BoxDefaultStacked.html
  <div class="lzBox BoxDefaultStacked {{extra_classes}}" data-apply="{{apply}}" data-id="{{id}}" data-client="{{client}}" data-len="{{elem_len}}">
	{% for t in tabs %}
		{{ t.html }}
	{% endfor %}
  </div>

templates/common/BoxDefaultTabbed.html
  <div class="lzBox BoxDefaultTabbed {{extra_classes}}" data-id="{{id}}" data-client="{{client}}" data-len="{{elem_len}}">
    <div class="topRight">

  {% if topRightIcon %} 
      <div class="topRightIcon">
        <img class="topRightImg tooltip" src="{{icon_path}}" title="{{tooltipText}}" />
      </div>
  {% endif %}

  {% if is_collapsible %}
      <div class="collapseButton">
        -
      </div>
  {% endif %}
    </div>

  {% if title %}
    <div class="boxTitle">
      {{title}}
    </div>
  {% endif %}

    <div class="boxContent">
    <div class="{% ifnotequal tabs|length 1 %} boxTabs {% endifnotequal %} {{tab_style}}">
      {% ifnotequal tabs|length 1 %}
      <ul class="tabs">
      {% for t in tabs %}
        {% if t.is_default %}
          <li> <a href="#tabdiv{{id}}{{t.id}}" title="tabdiv{{id}}{{t.id}}"><span>{{t.title.text}}</span></a></li>
        {% else %}        
          <li> <a href="{% url ajax_url %}?data_id={{t.title.data_id}}" title="tabdiv{{id}}{{t.id}}"><span>{{t.title.text}}</span></a></li>
        {% endif %}
      {% endfor %}
      </ul>
      {% endifnotequal %}
        <div class="tabContent">
        {% for t in tabs %}
          {% if t.is_default %}
            <div class="panes" id="tabdiv{{id}}{{t.id}}" data-next="{{Next.data_id}}"> 
             {{ t.html }}
            </div>
          {% endif %}
            <div class="panes" id="tabdiv{{id}}{{t.id}}" data-next="{{Next.data_id}}">
            </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>

templates/common/BoxEmpty.html
<div class="lzBox BoxEmpty">
<!--
{% if title %}
  <div class="boxTitle">
    {{ title }}
  </div>
{% endif %}
-->
{% for t in tabs %}
  {{ t.html }}
{% endfor %}
</div>

templates/common/BoxTabbed.html
  <div class="BoxTabbed {{extra_classes}}" data-id="{{id}}" data-client="{{client}}" data-len="{{elem_len}}">

  {% if title %}
    <div class="boxTitle">
      {{title}}
    </div>
  {% endif %}

    <div class="boxContent">
    <div class="{% ifnotequal tabs|length 1 %} boxTabs {% endifnotequal %} {{tab_style}}">
      {% ifnotequal tabs|length 1 %}
      <ul class="tabs">
      {% for t in tabs %}       
          <li> <a href="#{{t.id}}" title="{{t.desc}}"><span>{{t.title}}</span></a></li>
      {% endfor %}
      </ul>
      {% endifnotequal %}
        <div class="tab_container">
        {% for t in tabs %}
            <div class="tab_content hidden" id="{{t.id}}""> 
             {{ t.html }}
            </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>

templates/common/ElementDefault.html
{% load extra_tags %}
<div class="lzElement ElementDefault {{extra_classes}}" data-id="{{elem_id}}">
{% for l in lines %}
  <div class="itemHtml">
    <div class="lzLine line_{{l.class}}">
      {% for n in l %}
        {{ n|render_node }}
      {% endfor %}
    </div>
    {% include 'common/ShareBar.html' %}
  </div>

<!--
  <div class="itemImages">
{% for icon in i.icons %}
    <img class="itemImage tooltip" src="{{icon.path}}" title="{{icon.tooltipText}}" />
    <img class="itemImage tooltip" src="{{icon.path}}" title="{{icon.tooltipText}}" />
{% endfor %}
  </div>
-->

{% if has_popup %}
  <div class="itemPopup">
    <div class="popupCollapse">
      -
    </div>
    <div class="popupHtml">
      Loading...
    </div>
  </div>
{% endif %}
{% endfor %}
</div>
<div class="RASeparator">

</div>

templates/common/TabDefault.html
<div class="lzTab TabDefault" data-id="{{id}}">
{% autoescape off %}
  {{display_title}}
  {% for e in elements %}
    <div class="{% cycle 'elementEven' 'elementOdd' %}">
   {{ e }}
    </div>
  {% endfor %}

    <div class="tabBtns">
      {% if Prev %}
      <div class="tabPrevBtn tabNav" data-id="{{Prev.data_id}}">
        Previous
      </div>
      {% endif %}
      {% if Next %}
      <div class="tabNextBtn tabNav" data-id="{{Next.data_id}}">
        Next
      </div>
      {% endif %}
    </div>
{% endautoescape %}

</div>

templates/common/TabEmpty.html
{% for e in elements %}
  {{ e }}
{% endfor %}

templates/common/TabRA.html
<div class="lzTab RATab">
{% autoescape off %}
  {{display_title}}

  <div class="elements">
    {% for e in elements %}
      <div class="{% cycle 'elementEven' 'elementOdd' %}">
     {{ e }}
      </div>
    {% endfor %}
  </div>
  {% ifequal elements|length 0 %}
    <div class="RAEmpty">
      {% if desc %}
        {{desc}}
      {% else %}
        Sorry, no matching results found.
      {% endif %}
    </div>
  {% endifequal %}
      <div class="tabBtns">
        {% if Next %}
        <div class="tabNextBtn tabNav" data-id="{{Next.data_id}}">
          More
        </div>
        {% endif %}
      </div>
{% endautoescape %}
</div>

templates/common/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %} Welcome to Quote {% endblock %}</title>
  <script type="text/javascript" src="/static/js/jquery.js"></script>
  {% block extra_head %}
  {% endblock %}

</head>

<body>
  {% block js_templates %} {% endblock %}
  <div id="wrapper">
  
  {% block header %} {% endblock %}
  {% block main_body %} {% endblock %}
  </div>
</body>

</html>

templates/master/ElementCreateQuote.html
<div class="create_quote">    
	<div id="error"></div>
    <form method="POST" action="." class="transform" id="cquote">
        <div class="rowElem">
        	<div class="saveRowElem">
        		<a href="#" class="btn1" id="saveq" title="Save New Quote"><span><span><b>&nbsp;</b><u>Save&nbsp;Quote</u></span></span></a>
			</div>
			<div class="rowElem">
				<div class="labelrowElem" id="makePublic">
            		<label>Make&nbsp;Quote&nbsp;Public</label>
        		</div>
				<div class="quoteInput">
					<input type="checkbox" name="is_public" id="id_public">
				</div>
			</div>
        </div>
        <div class="rowElem">
        	<div class="labelRowElem">
			<label>Title&#42;</label><br/>     
            		<input id="id_title" class="side_text help_input" type='text' name='title'/>
        	</div>
		<div class="quoteInput">
            		<textarea name='text' id="id_text"></textarea>
        	</div>
	</div>
        <div class="rowElem">
			<div class="rowElemLeft">
            	<div class="labelRowElem">
            		<label>Quote Source</label>
            	</div>
        		<div class="quoteInput">
            		<select name="doctype">
                		{% for id, name in types %}
                		<option value="{{id}}">{{name}}</option>
                		{% endfor %}
        			</select>
				</div>
			</div>
			<div class="rowElemLeft" style="margin-left: 10px">
            	<div class="labelRowElem">
            		<label>Author/Court</label>
				</div>
        		<div class="quoteInput">
            		<input type="text" class="text_input" name="author" id="id_author"/>
        		</div>
			</div>
		</div>
        <div class="clear"></div>
		<div class="rowElem">
			<div class="labelRowElem">
				<label>Tags (comma separated)</label>
			</div>
			<div class="quoteInput">
            	<input type="text" class="text_input" name="tag" id="id_tag"/>
        	</div>
		</div>
        
        <div class="rowElem">
            <div class="labelRowElem">
				<label>Reference/URL</label>
			</div>
        	<div class="quoteInput">
            	<input type="text" class="text_input" name="reference" class="reference"/>
        	</div>
			<div>
				<a id="add_reference" href="#" class="btn1" title="Add Another Reference"><span><span><b>&nbsp;</b><u>+</u></span></span></a>
			</div>
			<input type="hidden" name="data_id" value="{{data_id}}"/>
		</div>
		<div class="saveRowElem">
				<a href="#" class="btn1" id="saveq" title="Save New Quote"><span><span><b>&nbsp;</b><u>Save&nbsp;Quote</u></span></span></a>
		</div>
    </form>
</div>

{% if not user %}
<div id="cquote_anon_user" class="hidden">
    <form id="anon_user_form">
	<div class="error"></div>
        <div class="rowElem">
            <div class="labelRowElem">
		<label>Your Email (to send you a password)</label>
	    </div>
	    <div class="quoteInput">
    		<input type="text" class="text_input" name="email" id="id_email"/>
	    </div>
	</div>
        <div class="rowElem">
	    <div class="labelRowElem">
		<label>Your&nbsp;Password</label>
	    </div>
	    <div class="quoteInput">
		<input type="text" class="text_input" name="code" id="id_code"/>
	    </div>
	</div>
	<input type="hidden" name="data_id" value="{{create_login_user}}"/>
	<div class="saveRowElem">
		<a href="#" class="btn1" id="save_anon" title="Submit"><span><span><b>&nbsp;</b><u>Submit</u></span></span></a>
	</div>
	<div class="message"></div>
    </form>
</div>
<a id="inline" href="#anon_user_form"></a>
{% endif %}
<script type="text/javascript">
    $(function(){
	function submit_createQuote(){
           var data = $('form#cquote').serialize();
	   $.get(AJAX_URL, data, function(json){
                 if(json.success){
                    window.location = json.url;
                 } else {
                    $('#error').html(json.reason);
                 }
            });
        }
	$('a#inline').fancybox({
					    'autoDimensions'	: false,
					    'width'         	: 350,
					    'height'        	: 210,
					    'transitionIn'	: 'none',
					    'transitionOut'	: 'none',
					    'onStart'		: function(){$('form#anon_user_form .error').html('');$('form#anon_user_form .message').html('');$('form#anon_user_form')[0].reset();}
				    });
	$('#save_anon').live('click', function(){$('#anon_user_form').submit(); return false;});
	$('#anon_user_form').validate({
	    submitHandler: function(form){
				var data = $('form#anon_user_form').serialize();
				$.get(AJAX_URL, data, function(json){
				    if(json.success){
					if(json.submit){submit_createQuote();} else {$('form#anon_user_form .message').html(json.message);}
				    } else {
					$('form#anon_user_form .error').html(json.reason);
				    }
				});
			    },
	    rules: {
			'email': {
                                email: true,
                                required: function(element){ return $('#id_code').val() == '';}
                                
                        },
                        'code': {
                                required: function(element){ return $('#id_email').val() == '';}
                                
                        }
	    },
	    messages:{
			'email': '<br/>You must provide an email address to receive your password. If you already have a password, enter it below.',
			'code': '<br/>You must provide an email address to receive your password. If you already have a password enter it here.',
	    }
	    
	});
        $('#saveq').live('click', function(){if($('#id_title').val() == 'Quote Title...'){$('#id_title').val('');}$('#cquote').submit(); return false;});
        $('#cquote').validate({
            debug: false,
            submitHandler: function(form) {
			    if ($('#id_public:checked').length == 0 && USER==false){
				$('a#inline').trigger('click');
			    } else {
				submit_createQuote();
			    }
                        },
            rules: {    
                        'title': 'required',
                        'text': 'required'
                        /*'email': {
                                email: true,
                                required: function(element){ return !($('#id_public:checked').length || $('#id_code').val() != '');}
                                
                        },
                        'code': {
                                required: function(element){ return !($('#id_public:checked').length || $('#id_email').val() != '');}
                                
                        }*/
                        
                    },
        messages: {
                    'title': 'You must provide a title for the Quote.',
                    'text': 'You must provide text for the Quote.',
                    /*'email': '<br/>For private quotes, either provide an email (your QuoteBin code will be sent here) or your QuoteBin code',
                    'code': '<br/>For private quotes, either provide an email (your QuoteBin code will be sent here) or your QuoteBin code'*/
                }

        });
        $('.remove_ref').live('click', function(){       
            $(this).closest('#referenceAdded').remove();
        });
       $('#add_reference').live('click', function(){
            $(this).parent().before($('<div class="quoteInput" id="referenceAdded"><input type="text" class="text_input" name="reference"/>
                                                    <div style="float:right; margin-right: 120px; margin-top: 7px;">
                                                        <a class="remove_ref clickable" title="Remove Reference">&times</a>
                                                    </div>
                                </div>'));
            return false;
       });

    });
</script>

templates/master/ElementFeedback.html
<div class="">
<div class="slide-out-div hidden">
        <a class="handle" href=".">Feedback</a>
        <script type='text/javascript' src='http://crowdsound.com/widgets/init?&amp;aid=4065&amp;w_uname={{username}}&amp;x_ref={{userid}}&amp;button_text=Leave Feedback'></script>
</div>
</div>

templates/master/ElementHeader.html
<div class="header">
    <div class="header_wrapper">
		<img src="/static/images/master/tabulaw_logo.png" class="header_logo"></img>
		<div class="header_right">
			<div class="user_links">
				<a href="/">Home</a>
					{% if user %}
					&nbsp;|&nbsp;
					<a href="/logout">Logout</a>
					{% else %}
					 |&nbsp;<a href="login">Sign&nbsp;In</a>&nbsp;|&nbsp;<a href="get_code">Register</a>
                	{% endif %}
			</div>
			{% if show_cq %}
			<div class="create_new_quote"><img src="/static/images/master/new_quote.png"/><a id="create_new_quote" href="/cq" title="Create Quote">NEW&nbsp;QUOTE&nbsp;</a></div>
			{% endif %}
		</div>
		<div class="hidden">
            <form id="get_code_form">
                <div class="error"></div>
		Enter an email address to send your password.<br/>
                <input type="text" class="side_text help_input" value="Email Address..." name="email" id="id_email_code"/>
                <input type="hidden" name="data_id" value="{{data_id}}"/>
                <input type="submit" value="Submit"/>
            </form>
        </div>
    </div>
    <div class="clear"></div>
    <div id="flash_messages" style="position:absolute; top:95px; margin-left: 20px;" class="info hidden"></div>
</div>

templates/master/ElementLogin.html
<div class="login">
    <div class="login_error hidden">asdasd</div>
    <form class="login_form transform">
        <div class="rowElem">
            <label for="id_login_email">Email</label>
        </div>
        <div class="rowElem">
            <input id="id_login_email" type="text" name="username"/>
        </div>
        <div class="rowElem">
             <label for="id_login_pass">Password</label>
        </div>
        <div class="rowElem">
            <input id="id_login_pass" type="password" name="password"/>
        </div>
        <div class="rowElem">
            <input type="hidden" name="data_id" value="{{data_id}}"/>
            <input type="hidden" name="ts" value="{{ts}}"/>
            <input id="login_btn" type="image" value="submit" src="/static/images/login.png"/>
        </div>
    </form>
</div>

templates/master/ElementQList.html
{% autoescape off %}
<div style="width:310px;">
    <div class="qoutelist_head" style="background: #e5e5e5">
        <div class="title clickable" style="font-weight: bold; font-size: 12px; float:left; margin-top: 5px; margin-left: 5px; width: 260px">{{title}}</div>
        {% if is_owner %}
        <div class="icon quote_delete clickable" data-id="{{delete}}" style="float:right"><img src="/static/images/master/icon_del.png"/></div>
        {% endif %}
        <div class="icons" style="float:right"><a href="/quote/{{link}}"><img src="/static/images/master/icon_source.png"/></a></div>
        <div class="clear"></div>
    </div>
    <div class="small" style="color: #737373; margin-left: 10px; margin-top: 5px;">{{author}} &nbsp; ({{created_date}})</div>
    <div class="slide" style="margin-top: 5px;margin-left: 10px; border-left: 3px solid #C2E0E0; padding-left: 15px; width:260px;">
        {{text|truncatewords:20}}<br/>
    </div>
        <!--div class="slider clickable">Share Via Email</div>
            <div class="slide2">
                <form class="share_email">
                    <label>From</label>
                    <input type="text" name="from"/><br/>
                    <label>To</label>
                    <input type="text" name="to"/>
                    <input type="hidden" name="data_id" value="{{share}}"/>
                    <input type="submit" value="Share"/>
                </form>
            </div>
    </div-->
</div>
{% endautoescape %}

templates/master/ElementSearch.html
<div class="search_quote col" data-id="{{data_id}}">
    <form method='post' action='/search'>
        <div class="search_input">
        <input id="main-query" class="side_text help_input" value="Search Quote Titles..." type='text' name='q' value='{{q}}'/>
        </div>
        <div class="search_btn_div">
            <a href="#" class="btn1"><span><span><b>&nbsp;</b><u>Search</u></span></span></a>
        </div>
        <div class="clear"></div>
    </form>
</div>

<div class="clear"></div>

templates/master/ElementSide.html
<div class="side_element" >
    <!--a href="{% url ajax_url %}/?data_id={{data_id}}&code={{code}}">{{name}}</a-->
    <a href="/project/{{code}}">{% ifequal name 'All' %} Public Quotes {% else %} {{name}} {% endifequal %}</a>
</div>

templates/master/ElementSignUp.html
<div class="signup">
    <div class="signup_error hidden">asdasd</div>
    <form class="signup_form transform">
            <div class="rowElem">
                <label for="id_signup_email">Email</label>
            </div>
            <div class="rowElem">
                <input id="id_signup_email" type="text" name="username"/>
            </div>
            <div class="rowElem">
                <label for="id_signup_pass">Password</label>
            </div>
            <div class="rowElem">
                <input id="id_signup_pass" type="password" name="password"/>
            </div>


            <div class="rowElem">
                <label for="id_signup_pass2">Repeat Password</label>
            </div>
            <div class="rowElem">
                <input id="id_signup_pass2" type="password" name="password2"/>
            </div>
        <div class="rowElem">
            <input type="hidden" name="data_id" value="{{data_id}}"/>
            <input id="signup_btn" type="image" value="submit" src="/static/images/signup.png"/>
        </div>
    </form>
</div>

templates/master/PageLanding.html
{% extends 'base.html' %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="/static/css/master/PageTwoColumnCommon.css" />
{% endblock %}

{% block header %}
    {{ header }}
{% endblock %}

{% block main_body %}
  <div class="main_body">
    <div id="leftCol">
      {{ boxes.0 }}
      {{ boxes.1 }}
    </div>
    <div id="centerCol">
      {{ boxes.2 }}
    </div>
    <div class="clear"></div>

  </div>


{% endblock %}

templates/master/PageMain.html
{% extends 'base.html' %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="/static/css/master/PageMain.css" />
<link rel="stylesheet" type="text/css" href="/static/css/master/PageTwoColumnCommon.css" />
{% endblock %}

{% block header %}
    {{ header }}
{% endblock %}

{% block main_body %}
  <div class="main_body">
    <div class="col centre_col">
      {{ boxes.0 }}
      {{ boxes.1 }}
    </div>
    <div class="col right_col">
      {{ boxes.2 }}
      {{ boxes.3 }}
      {{ boxes.4 }}
      {{ boxes.5 }}
    </div>
  </div>
    {{ footer }}

{% endblock %}

templates/master/TabReview.html
<div class="TabReview" data-id="{{id}}">
{% autoescape off %}
  {{display_title}}
  {% for e in elements %}
    <div class="{% cycle 'elementEven' 'elementOdd' %}">
   {{ e }}
    </div>
  {% endfor %}

    <div class="tabBtns">
      {% if Prev %}
      <div class="tabPrevBtn tabNav" data-id="{{Prev.data_id}}">
        Previous
      </div>
      {% endif %}
      {% if Next %}
      <div class="tabNextBtn tabNav" data-id="{{Next.data_id}}">
        Next
      </div>
      {% endif %}
    </div>
{% endautoescape %}

</div>

templates/master/TabSearchResult.html
<div style="width:310px">
{% for e in elements %}
  {{ e }}
{% endfor %}
</div>